version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - "2407:6379"
    

  app1:
    build: 
      context: ./CircleSync
    ports: 
      - "5000:5000"
    depends_on:
      - redis

  app2:
    build: 
      context: ./Microservice
    ports:
      - "8000:8000"
    depends_on:  
      - redis